[institution]
name            = "Thal University Bhakkar"
department      = "Department of Computer Science & Information Technology"
contact_email   = "computing@tu.edu.pk"
academic_year   = "2025-2026"

[institution.social]
website  = "https://tu.edu.pk"